hostname: myhost
mounts:
- - /dev/vdb
  - /mnt/data
  - ext4
  - ""
write_files:
  - content: |
      {
      "data-root": "/mnt/data/docker-data/"
      }
    path: /etc/docker/daemon.json
ssh_authorized_keys:
  - ssh-rsa AAA...ZZZ example1@rancher
rancher:
  ssh:
    keys:
      dsa: |+
        -----BEGIN DSA PRIVATE KEY-----
        sample
        -----END DSA PRIVATE KEY-----
      dsa-pub: |+
        ssh-dss sample root@omydomain.com
      ecdsa: |+
        -----BEGIN EC PRIVATE KEY-----
        sample
        -----END EC PRIVATE KEY-----
      ecdsa-pub: |+
        ecdsa-sha2-nistp256 sample root@mydomain.com
      ed25519: |+
        -----BEGIN OPENSSH PRIVATE KEY-----
        sample
        -----END OPENSSH PRIVATE KEY-----
      ed25519-pub: |+
        ssh-ed25519 sample root@mydomain.com
      rsa: |+
        -----BEGIN RSA PRIVATE KEY-----
        sample
        -----END RSA PRIVATE KEY-----
      rsa-pub: |+
        ssh-rsa somekey root@mydomain.com
